name: "letsencrypt"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  lego:
    image: "11notes/lego:5.3.1"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      LEGO_CONFIG: |-
        challenges:
          cf:
            dns:
              provider: cloudflare
              envFile: /run/secrets/cf
              resolvers:
                - 8.8.8.8:53
                - 1.1.1.1:53
                - 9.9.9.9:53

        certificates:
          ${FQDN}:
            challenge: cf
            domains:
              - "${FQDN}"
              - "*.${FQDN}"
            renew:
              reuseKey: false
            pfx:
              password: lego1234
              format: SHA256

        storage: /lego/var
        accounts:
          default:
            acceptsTermsOfService: true
        log:
          level: info
          format: text
    volumes:
      - "lego.etc:/lego/etc"
      - "lego.var:/lego/var"
    tmpfs:
      # needed for read-only
      - "/run/secrets:uid=1000,gid=1000"
    secrets:
      - "cf"
    networks:
      frontend:
    restart: "always"

volumes:
  lego.etc:
  lego.var:

networks:
  frontend:

secrets:
  cf:
    file: "./cloudflare.txt"