name: "letsencrypt"
services:
  lego:
    image: "11notes/lego:1.0.0"
    dns:
      - "8.8.8.8"
      - "9.9.9.9"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
      LEGO_CONFIG: |-
        domains:
          - name: "domain.com"
            fqdns:
              - "*.domain.com"
              - "domain.com"
            commands:
              - "--dns"
              - "rfc2136" 

          - name: "porkbun.com"
            fqdns:
              - "*.porkbun.com"
              - "porkbun.com"
            commands:
              - "--dns"
              - "porkbun"    
        global:
          LEGO_EMAIL: "info@domain.com"
          RFC2136_NAMESERVER: "ns.domain.com"
          RFC2136_TSIG_ALGORITHM: "hmac-sha512"
          RFC2136_TSIG_KEY: "lego"
          RFC2136_TSIG_SECRET: ${RFC2136_TSIG_SECRET}
          PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
          PORKBUN_API_KEY: ${PORKBUN_API_KEY}
    volumes:
      - "etc:/lego/etc" 
      - "var:/lego/var"
    networks:
      frontend:
    restart: "always"
volumes:
  etc:
  var:
networks:
  frontend: